import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "@/features/query/QueryProvider";

import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          {children}
          <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                background: "#4E876D",
                color: "#fff",
              },
              success: {
                iconTheme: {
                  primary: "#fff",
                  secondary: "#4E876D",
                },
              },
              error: {
                style: {
                  background: "#ef4444",
                  color: "#fff",
                },
                iconTheme: {
                  primary: "#fff",
                  secondary: "#ef4444",
                },
              },
            }}
          />
        </QueryProvider>
      </body>
    </html>
  );
}
